name: PRレビュアーのアサイン通知（Teamsにチャットを送信）

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: GitHubユーザー名をメールアドレスに変換してTeamsの個人チャットへ通知する
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          REVIEWER_LOGIN: ${{ github.event.requested_reviewer.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          REPO_NAME: ${{ github.repository }}
        run: |
          echo "Reviewer username: $REVIEWER_LOGIN"

          # kentem- から始まっていない場合は通知をスキップ
          if [[ "$REVIEWER_LOGIN" != kentem-* ]]; then
            echo "kentem-から始まっていないユーザーなので通知スキップ: $REVIEWER_LOGIN"
            exit 0
          fi

          # 「kentem-」のプレフィックスを削除（最初のハイフン以降を取得）
          # 例: kentem-ke-kudo → ke-kudo
          USER_PART="${REVIEWER_LOGIN#*-}"

          # ドメインを付けてメールアドレス完成
          EMAIL="${USER_PART}@kentem.co.jp"

          echo "Generated email: $EMAIL"

          # Power Automate Webhook に送信
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "pr_url": "$PR_URL",
            "pr_title": "$PR_TITLE",
            "repository": "$REPO_NAME",
            "assigned_user_email": "$EMAIL",
            "attachments": []
          }
          EOF
