name: Teamsにチャットを送信

on:
  workflow_call:
    inputs:
      send_to:
        required: true
        type: string
      title:
        required: true
        type: string
      repository:
        required: true
        type: string
      event:
        required: true
        type: string
      event_url:
        required: false
        type: string
      message:
        required: true
        type: string
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: GitHubユーザー名をメールアドレスに変換してTeamsの個人チャットへ通知する
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          SEND_TO="${{ inputs.send_to }}"
          TITLE="${{ inputs.title }}"
          REPOSITORY="${{ inputs.repository }}"
          REPOSITORY_URL="https://github.com/ks-kentem/${{ inputs.repository }}"
          EVENT="${{ inputs.event }}"
          EVENT_URL="${{ inputs.event_url }}"
          MESSAGE="${{ inputs.message }}"

          echo "Username: $SEND_TO"

          # kentem- から始まっていない場合は通知をスキップ
          if [[ "$SEND_TO" != kentem-* ]]; then
            echo "kentem-から始まっていないユーザーなので通知スキップ: $SEND_TO"
            exit 0
          fi

          # 「kentem-」のプレフィックスを削除（最初のハイフン以降を取得）
          # 例: kentem-ke-kudo → ke-kudo
          USER_PART="${SEND_TO#*-}"

          # ドメインを付けてメールアドレス完成
          EMAIL="${USER_PART}@kentem.co.jp"

          echo "Generated email: $EMAIL"

          # Power Automate Webhook に送信
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "send_to": "$EMAIL",
            "title": "$TITLE",
            "repository": "$REPOSITORY",
            "repository_url": "$REPOSITORY_URL",
            "event": "$EVENT",
            "event_url": "$EVENT_URL",
            "message": "$MESSAGE"
          }
          EOF
